/* This file is autogenerated, do not edit*/
#include "PCP_automoc.dir/moc_rOg_image_L4Z25VNYTV32PG.cpp"
#include "PCP_automoc.dir/moc_actionwidget_YGJIWX2KPRLBYN.cpp"
#include "PCP_automoc.dir/moc_calibrationwid_PCCIFWUGI3RV5G.cpp"
#include "PCP_automoc.dir/moc_mainwindow_LQHKWQ4N6L2ZOQ.cpp"
#include "PCP_automoc.dir/moc_widget_LD5AFFWRDBITAG.cpp"
